name: Check File Sizes for HF Space
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: write-all

jobs:
  check-file-sizes-for-hf-space:
    runs-on: ubuntu-latest
    steps:
      - name: Check files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760 # 10MB limit by HF Space
